server:
  port: 0

#將此服務註冊至Eureka伺服器
eureka:
  instance:
    instance-id: eureka-client-instance-id #自定义服务名称信息
    prefer-ip-address: true #显示访问路径的 ip 地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:3303/eureka/
#enable actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"