server:
  port: 3305

eureka:
  server: #關閉自我保護，並修改[檢查服務是否失效]的時間，若是服務真的失效，將直接移除服務
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: localhost
  client: #此為服務發現Server，不需註冊服務
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:3303/eureka/,http://localhost:3304/eureka/,http://localhost:3305/eureka/