spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  profiles:
      active: sit

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/SpringSecurity
    username: 
    password: 
server:
  port: 9088
  
logging:
  level:
    com:
      willy:
        spring:
          mapper: debug