spring:
  application:
    name: eureka-producer
  profiles:
    active: staging
info:
  app.name: eureka-producer
  company.name: willy
  build.aetifactId: @project.artifactId@
  build.version: @project.version@