server:
  port: 3301
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huzhicheng/config-only-a-demo #配置文件所在仓库
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录