// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.willy.grpc.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *field number，有多個參數即按順序遞增
   * </pre>
   *
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <pre>
   *field number，有多個參數即按順序遞增
   * </pre>
   *
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string request1 = 2;</code>
   */
  java.lang.String getRequest1();
  /**
   * <code>string request1 = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequest1Bytes();
}
