spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/SpringBootLogBack;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
    username: 
    password: 
  jpa: 
    hibernate: 
         ddl-auto: none
    show-sql: true