version: "3.5"

# You will see environment variables here
# You can find them in C:\work\hybris_1811_docker\hybris_docker\.env

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - "5772:5672" #program port
      - "16672:15672" #web prot
    container_name: rabbitmq