server:
  port: 8004

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://localhost:8000/eureka/
      
spring:
  application:
    name: cloud-customer-dao-ribbon
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  profiles: 
    active: bak
