spring:
  mail:
    host: 127.0.0.1
    port: 25
    username: root
    password: root
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory