spring:
  application:
    name: eureka-client-1
  profiles:
    active: dev
info:
  app.name: eureka-client-1
  company.name: willy
  build.aetifactId: @project.artifactId@
  build.version: @project.version@