server:
  port: 3301
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/willy50414z/Sample #配置文件所在仓库
          default-label: master #配置文件分支
          search-paths: Java/Springboot/SpringClould/cloud/config-server/src/main/resources/config  #配置文件所在根目录