
package com.test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.4
 * Mon Jun 11 14:23:34 CST 2018
 * Generated source version: 3.2.4
 */

@XmlRootElement(name = "echoResponse", namespace = "http://test.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "echoResponse", namespace = "http://test.com/")

public class EchoResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

